__version__ = "0.0.1"
__description__ = "Approximate driving speeds on location-specific road classes using public GPS trace data."
__author__ = "Richard Chen"
__author_email__ = ""
__url__ = "https://github.com/OpenStreetMapSpeeds/conflation"
__title__ = "conflation"
